# https://github.com/lowlighter/metrics
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          config_display: columns

          # github activity: https://github.com/lowlighter/metrics/blob/master/source/plugins/activity/README.md
          plugin_activity: yes
          plugin_activity_limit: 10    # Limit to 5 events
          plugin_activity_days: 0    # Keep only events from last 14 days (can be set to 0 to disable limitations)
          plugin_activity_filter: all # Show all events (use table above to filter events types)
          
          # https://github.com/lowlighter/metrics/blob/master/source/plugins/isocalendar/README.md
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year # Display full year instead of half year
          
          # https://github.com/lowlighter/metrics/blob/master/source/plugins/lines/README.md
          plugin_lines: yes
          
          # https://github.com/lowlighter/metrics/blob/master/source/plugins/skyline/README.md
          plugin_skyline: yes
          plugin_skyline_year: 0   # Set to 0 to display current year
          plugin_skyline_frames: 120        # Use 60 frames (half-loop)
          plugin_skyline_quality: 1        # Set image quality
          
          # https://github.com/lowlighter/metrics/blob/master/source/plugins/stars/README.md
          plugin_stars: yes
          plugin_stars_limit: 5 # Limit to 4 entries
          
          # https://github.com/lowlighter/metrics/blob/master/source/plugins/topics/README.md
          plugin_topics: yes
          plugin_topics_sort: stars    # Sort by most starred topics
          plugin_topics_mode: mastered # Display icons instead of labels
          plugin_topics_limit: 0       # Disable limitations
          
          # https://github.com/lowlighter/metrics/blob/master/source/plugins/music/README.md
          plugin_music: yes
          plugin_music_limit: 4                   # Limit to 4 entries
          plugin_music_provider: apple
          plugin_music_mode: playlist
          plugin_music_playlist: https://embed.music.apple.com/jp/playlist/my-favs/pl.u-oZylKEWC0eRoYV?l=en # Use extracted playlist link
          
