# https://github.com/lowlighter/metrics
name: Metrics
on:
  schedule: [{cron: "0 0 0/7 * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_twemoji: yes
          config_gemoji: yes
          # https://github.com/lowlighter/metrics/blob/master/source/plugins/isocalendar/README.md
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          # https://github.com/lowlighter/metrics/blob/master/source/plugins/lines/README.md
          plugin_lines: yes
          # https://github.com/lowlighter/metrics/blob/master/source/plugins/stars/README.md
          plugin_stars: yes
          plugin_stars_limit: 5
          # https://github.com/lowlighter/metrics/blob/master/source/plugins/music/README.md
          plugin_music: yes
          plugin_music_limit: 5
          plugin_music_provider: apple
          plugin_music_mode: playlist
          plugin_music_playlist: https://embed.music.apple.com/jp/playlist/my-favs/pl.u-oZylKEWC0eRoYV?l=en
          
